prefijo_capa_agujeros = "int" 
max_area = 100
num_intermedios_linea = 10
num_intermedios_circulo = 10
num_intermedios_spline = 0.1
presicion = 6
indice_punto_contorno = 0
indice_punto_agujero = 0
op_vtk=False
op_npz=True
op_csv=True
op_vis=True
